language: go
sudo: true
services:
  - docker

matrix:
  allow_failures:
  - go: master
  include:
  - os: linux
    go: 1.14.x
    cmetro2e:
      directories:
      - "$HOME/.cmetro2e/go-build"
      - "$GOPATH/pkg/mod"
  - os: linux
    go: master
  - os: osx
    go: 1.14.x
    cmetro2e:
      directories:
      - "$HOME/Library/Cmetro2es/go-build"
      - "$GOPATH/pkg/mod"
  - os: windows
    go: 1.14.x
    cmetro2e:
      directories:
      - C:\Users\travis\AppData\Local\go-build

before_install:
  - mkdir ./bin
  - export PATH=$PATH:$PWD/bin
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install -y make; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install -y mingw; export PATH=/c/tools/mingw64/bin:"$PATH";fi

before_script:
  - GOFILES=$(find . -type f -name '*.go' | grep -v vendor)
  - go mod graph

script:
  - make check

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - make dist

deploy:
  provider: releases
  api_key:
    secure: Ci3lExAdhYetE4YAbox2dJBdTSj5upqqy0G6KtZnvM0539IvGnkWhOlZemBDKsie1K+LwSAp4xRhOxM8Torauy5ZSzKgLc9qIxNlK5ME4ymIxTdPs6XMvI+zLgLk5H4G0ygbP9P4eX6dI0b4pmtQ13bKeuxTg3VXTUchsYOrJ4fce7jLxH87AFIgKwbOBMjByfEoaU/Z2T9yRFDspqT6SoBDONLq+vRWGukNqscGq0Olu+Rk03eVDkkcy7wFUgo4Hni+vu6JIW79BcKr1i4GmwZ17nct2RzubKYqfhtpTdx342GAg0mEMDDIMnyMBWME19A2eEqR3tS8xezuI9cRVRAeCp+NinvP38xsQzUjybLnm3B56cvE9m+V0VCp8H5m6/DfC/mbbjR02SQNGrSRF1QNAX3ltvXNw2iE+3U7SXybG6w8fxNFlM+/7Qcdy66Fqw/B13tDbGmD7rM8BnqmQYDLIMUnTy3OwSmcVa73pUP61uCw0N62emhGHdg/h1x4pXh/I4RaBBMcdpLQJ3vFtSh/IrcTQyKWUP0c+Fqvrdes8UFi/5LiCxnct+dmBt0gurTFRkmj+HWGlz4Z1BRobkC7CLbcScF5t8TnUNdJZ5+SQk8mcU1k2eJ0zDvs764+g3HedNvtdQIlq1/MmYiqpPy14AoybMmXd5oBFp5kSus=
  file_glob: true
  file:
    - bin/metro2*
  on:
    tags: true
    repo: moov-io/metro2
    go: 1.14.x
  skip_cleanup: true
